### ISSUE TITLE
Allow for more than one mapgame on a page

### ISSUE THREAD

**Issue by freejoe76** [denverpost/mapgame#10]

**Comment by vigorousnorth** [comment]
I'm working on a version that structures the `mapg.config` object as an array of objects, each of which contains a new target, and calls the `mapg.update_config(mapg_config[index])` function when a "next question" button gets pressed.

**Comment by freejoe76** [comment]
@vigorousnorth That makes sense -- the challenge is going to be sorting out situations where the object is referenced from outside the object:

https://github.com/denverpost/mapgame/blob/master/www/mapgame.js#L151
https://github.com/denverpost/mapgame/blob/master/www/mapgame.js#L176
https://github.com/denverpost/mapgame/blob/master/www/mapgame.js#L180

etc. oh but wait your approach would bypass that. Nevermind. That's a good idea.

**Comment by freejoe76** [comment]
This can be done with iframe'ing a particular URL on the mobile-friendly version of the site: http://extras.denverpost.com/app/mapgame/games/denver.html#iframe
