### ISSUE TITLE
tally.php

### ISSUE THREAD

**Issue by vigorousnorth** [denverpost/mapgame#17]
Would you mind committing your `tally.php` file to the repository? 

I found a link to this project on today's OpenNews call, and decided that I'd like to work on a multiple-question version here in Maine for the Portland Press Herald. Good stuff – thanks for sharing!

**Comment by freejoe76** [comment]
Sure!

**Comment by freejoe76** [comment]
Okay, the tally.php script is in there, it's fairly domain-specific and procedural which means there is plent of room for improvement. Ha. You'll need to set some environment vars to get the database connection working. https://github.com/denverpost/mapgame/blob/master/www/tally.php
